### ISSUE TITLE
Insstallation files

### ISSUE THREAD

**Issue by smurfkungen** [nbrightproject/NBrightPayPal#2]
I cannot find installation files. Is there a release for this project?

**Comment by leedavi** [comment]
Yes, Sorry the downloads are all over the place at the moment, I'm going to try and  move everything into 1 download area.

This one is here at the moment:  https://nbrightpaypal.codeplex.com/

**Comment by smurfkungen** [comment]
Hi thanks for your prompt reply!

Downloaded and installed, seems fine.

I wanted to remove manual payment and only use PayPal. Any ide as to how?

Also, wanted to setup development env for this solution. Can I install the setup package and the put in the source code folder under desktop folders and add the project to the solution, or do you suggest any other way?

Payment gateway development. I was thinking of doing in the same way. I think I saw some instruction of payment setup, but was not sure.

Thanks for your work. It seems really nice and I will check this stuff out now and hopefully use it and maybe able to contribute a little bit as well in the future.

Thanks again

Pedro

**Comment by smurfkungen** [comment]
Sorry to bother you again,

I found the doc and am installing dev. The only thing is that the folder structure was a little unclear. No I put the support folder NBrightBuy as in the image

[cid:image001.png@01D0F4C2.AB3DEF20]

Is that correct?

Thank you!

Pedro

**Comment by leedavi** [comment]
I can't see that image, but here are some link you might find useful,

http://nbsdocs.nbrightproject.org/Documentation/Developerguide/DevSetup.aspx

http://nbsdocs.nbrightproject.org/Documentation/Developerguide/PaymentGateway.aspx

To turn of the manual payments, go into the BO>Admin>PLugins and disactivate the "Manual Payment" plugin.
